-- 0014|00000011|F|FIS|AADH61021374A       |00003920|PRI|00005330|00|IGNACIO BERNAL NUM 4351 B                         |               |               |09|LOMAS DE MEMETLA              |0000001|MEXICO                        |00005|CUAJIMALPA DE MORELOS         |DF|                    |                    |052|FIS|HECTOR JESUS ANAYA DOLL                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                            |00001|605     |          |          |00001|G03     |2022-02-02|          |
-- 0014|00000014|F|PER|SAOB651126LK7       |00076250|PRI|00086302|  |                                                  |               |               |  |PRESCOTT                      |       |MEXICO                        |     |CUAUHTEMOC                    |  |                    |                    |001|PER|OBDULIA BETINA SABINA                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                            |00000|        |          |          |00000|        |          |          |


INSERT INTO "OPICS"."OPICS_MX_TMP_PRAC" (
    FEC_PROCESO,
    PECDGENT,
    PENUMPER,
    PETIPPER,
    PEORIRFC,
    PENUMRFC,
    PECODFIS,
    PETIPDOM,
    PECODPOS,
    PETIPVIA,
    PENOMCAL,
    PENUMEXT,
    PENUMINT,
    PETIPASE,
    PENOMASE,
    PENOMLOC,
    PEDESLOC,
    PENOMCOM,
    PEDESCOM,
    PECODPRO,
    PEENTCAM,
    PEULTCAM,
    PECODPAI,
    PEORINOM,
    PENOMRAZ,
    PEREGCAP,
    PESECREF,
    PECVEFIS,
    PEFECINI,
    PEFECFIN,
    PESECUSO,
    PECVEUSO,
    PEFECINI2,
    PEFECFIN2
)
VALUES
(   
    '2024-04-11',
    '0014',
    '00000011',
    'F',
    'FIS',
    'AADH61021374A       ',
    '00003920',
    'PRI',
    '00005330',
    '00',
    'IGNACIO BERNAL NUM 4351 B                         ',
    NULL,
    NULL,
    '09',
    'LOMAS DE MEMETLA              ',
    '0000001',
    'MEXICO                        ',
    '00005',
    'CUAJIMALPA DE MORELOS         ',
    'DF',
    NULL,
    NULL,
    '052',
    'FIS',
    'HECTOR JESUS ANAYA DOLL'   ,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(   
    '2024-04-10',
    '0014',
    '00000014',
    'F',
    'PER',
    'SAOB651126LK7       ',
    '00076250',
    'PRI',
    '00086302',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'PRESCOTT                      ',
    NULL,
    'MEXICO                        ',
    NULL,
    'CUAUHTEMOC                    ',
    NULL,
    NULL,
    NULL,
    '001',
    'PER',
    'OBDULIA BETINA SABINA',
    NULL,
    '00000',
    NULL,
    NULL,
    NULL,
    '00000',
    NULL,
    NULL,
    NULL
)
;