INSERT INTO OPICS.OPICS_MX_TMP_PRAC (
    FEC_PROCESO,
    PECDGENT,
    PENUMPER,
    PETIPPER,
    PEORIRFC,
    PENUMRFC,
    PECODFIS,
    PETIPDOM,
    PECODPOS,
    PETIPVIA,
    PENOMCAL,
    PENUMEXT,
    PETIPASE,
    PENOMASE,
    PENOMLOC,
    PEDESLOC,
    PENOMCOM,
    PEDESCOM,
    PECODPRO,
    PEENTCAM,
    PEULTCAM,
    PECODPAI,
    PEORINOM,
    PENOMRAZ,
    PEREGCAP,
    PESECREF,
    PECVEFIS,
    PEFECINI,
    PEFECFIN,
    PESECUSO,
    PECVEUSO,
    PEFECINI2,
    PEFECFIN2
)
VALUES
(
    '12/17/2023',
    'Richart',
    'Sandbach',
    'error: undefined method first for nil:NilClass',
    'error: undefined method first for nil:NilClass',
    'Audley',
    'error: undefined method first for nil:NilClass',
    'error: undefined method first for nil:NilClass',
    '489 Montana Court',
    'error: undefined method first for nil:NilClass',
    'Flashspan',
    'Enköping',
    'error: undefined method first for nil:NilClass',
    'Delora',
    'Badajoz',
    '5th Floor',
    'Browsezoom',
    'Road',
    658,
    'Krona',
    'Euro',
    'SE',
    'Willie',
    'Multi-tiered dedicated definition',
    'Ruble',
    8,
    'Afghani',
    '1c4bd7a4-d91d-40d9-8c5a-6ded0ebbfdb8',
    '3a0d5a6a-9903-49a0-88cf-82601ce9927c',
    67,
    'Masasi',
    '7/9/2023',
    '12/19/2023'
),
(
    '12/17/2023',
    'Rodi',
    'Isaak',
    'error: undefined method first for nil:NilClass',
    'error: undefined method first for nil:NilClass',
    'Druhan',
    'error: undefined method first for nil:NilClass',
    'error: undefined method first for nil:NilClass',
    '8 Hollow Ridge Circle',
    'error: undefined method first for nil:NilClass',
    'Vitz',
    'Hongqi',
    'error: undefined method first for nil:NilClass',
    'Cinda',
    'Lazaro Cardenas',
    'Apt 489',
    'Brightbean',
    'Park',
    300,
    'Yuan Renminbi',
    'Peso',
    'CN',
    'Sheppard',
    'Devolved optimizing hardware',
    'Euro',
    10,
    'Euro',
    '604b5a1d-eae3-4f16-9af0-ae58999372cd',
    '59852474-6d1c-4ee2-9378-58c05a727d8a',
    58,
    'Ogden',
    '7/1/2023',
    '12/17/2023'
)
;
