SELECT 
    FEC_PROCESO||'|'||
    PECDGENT||'|'||
    PENUMPER||'|'||
    PETIPPER||'|'||
    PEORIRFC||'|'||
    PENUMRFC||'|'||
    PECODFIS||'|'||
    PETIPDOM||'|'||
    PECODPOS||'|'||
    PETIPVIA||'|'||
    PENOMCAL||'|'||
    PENUMEXT||'|'||
    PETIPASE||'|'||
    PENOMASE||'|'||
    PENOMLOC||'|'||
    PEDESLOC||'|'||
    PENOMCOM||'|'||
    PEDESCOM||'|'||
    PECODPRO||'|'||
    PEENTCAM||'|'||
    PEULTCAM||'|'||
    PECODPAI||'|'||
    PEORINOM||'|'||
    PENOMRAZ||'|'||
    PEREGCAP||'|'||
    PESECREF||'|'||
    PECVEFIS||'|'||
    PEFECINI||'|'||
    PEFECFIN||'|'||
    PESECUSO||'|'||
    PECVEUSO||'|'||
    PEFECINI2||'|'||
    PEFECFIN2||'|'||
FROM OPICS_MX_TMP_PRAC;